### ISSUE TITLE
Multiple PSFs input as images

### ISSUE THREAD

**Issue by pgee2000** [GalSim-developers/GalSim#660]
This is really a question.  I see from one of the demos that GalSim can read its PSF as an InterpolatedImage from a fits file image.  Is it also possible to use a multiple hdu fits file with many PSF images, and get it to use a different PSF for each galaxy through the yaml interface?

**Comment by rmjarvis** [comment]
Hmm.  It seems we don't have the option of using an hdu other than the first one for an InterpolatedImage (either in the python layer or with a yaml file).  That's an oversight that we could certainly fix.  

However, another option that might work for you would be to use a different file for each object.  Something like the following should work:
```
psf:
    type: InterpolatedImage
    image:
        type: FormattedStr
        format: "psffile_%03d.fits"
        items:
            - # Only one item here, which is the number to use for %03d
                type: Sequence
                first: 1
                # You could also use last or nitems if you wanted the sequence to repeat.
                # Otherwise, this will use the next number for each successive galaxy.
```
