### ISSUE TITLE
Adding a new top-level field to GalSim config.

### ISSUE THREAD

**Issue by shobhit16** [GalSim-developers/GalSim#760]
The basic idea is to run a particular analysis code that can be configured through a YAML script, without resorting to the other top-level fields for defining galaxies and PSFs. Is there a way to accomplish this with the current functionality of GalSim?

**Comment by rmjarvis** [comment]
I don't understand what you want to do here.  It would be helpful if you provided a strawman example of what you want to do.

If you just want to have your own custom code that reads in some new top level field in the YAML file and does something with it, including using some of the config functionality, that's certainly possible.  You can look at [demo8](https://github.com/GalSim-developers/GalSim/blob/master/examples/demo8.py) for an example of a python script the runs aspects of the config parser.

If you want to use the regular `galsim` executable to do mostly regular config parsing, but with some custom code for particular aspects of it, that's also possible, although only on master at the moment, and soon in version 1.4.  See some of the yaml files in examples/des.  e.g. [blend.yaml](https://github.com/GalSim-developers/GalSim/blob/master/examples/des/blend.yaml) and [meds.yaml](https://github.com/GalSim-developers/GalSim/blob/master/examples/des/meds.yaml) in particular.  There is also documentation about writing these cutom types in the v1.4 config documentation pages: e.g. [Value types](https://github.com/GalSim-developers/GalSim/wiki/Config-Values#custom-value-types), [Output types](https://github.com/GalSim-developers/GalSim/wiki/Config-Output#custom-output-types), etc.

If neither of these are what you meant, please provide a straw man yaml file for what you have in mind and I'll see if I can give you advice about how to make it happen.

**Comment by shobhit16** [comment]
@rmjarvis Ok. I think it would still be better to have an opinion on the way to go about this.

I have some Python code currently which builds a few galaxies, draws them and runs HSM on them. But at this point I am configuring it using PyYAML for a few parameters. What I eventually want to do is to run my code in a way similar to this:

`galsim test.yaml`

instead of

`python code.py test.yaml`

where the test.yaml should be capable of initiating my Python code as well as configuring it. My current YAML file looks something as this:

```
HSM_Comparison:
    # Number of galaxies that need to be processed
    ngal: 20
    # Location of the LSST Filters
    filter_data: /Users/apple/Git/GalSim/GalSim/examples/data
    # LSST Filter to be used (u,g,r,i,z,y) (Optional) (Defualt: r)
    filter: r
    # Output Filename (Optional) (Default: shapeData.h5)
    output_filename: shapeData.h5
    # Location of the COSMOS Catalog (if different from default) (Optional)
    #catalog_directory: /usr/local/share/galsim/COSMOS_25.2_training_sample
```

So as you see, I need to parse this file to define some parameters in my code as the number of galaxies I need to run my analysis on along with some other stuff, as specified in the comments above. Since, the definition of galaxies and PSFs is already embedded in my Python code, I don't need any control over defining them. So, an ideal situation would be where I can run my code in isolation while excluding the other top-level fields. 

I hope this makes it clear.
