### ISSUE TITLE
allow numpy calls in functions in configs

### ISSUE THREAD

**Issue by esheldon** [GalSim-developers/GalSim#776]
Allow either `numpy.` or `np.` calls, for example the following.  I know this works in other scenarios such as Eval so should be straightforward to implement

```
        type: GBeta
        g:
            # this didn't work, due to np.exp
            type: RandomDistribution
            function: "(1-x**2)**2 * np.exp( -0.5 * x**2 / 0.2**2 )"
            x_min: 0.0
            x_max: 1.0
        beta:
            type: Random

```
